# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    css_writer_service:
        class: CMSBundle\Services\CssWriter
    template_creator_service:
        class: CMSBundle\Services\TemplateCreator
    slug_survice:
        class: CMSBundle\Services\Slug
    form_helper_service:
        class: CMSBundle\Services\FormHelper