<?php

namespace CMSBundle\Repository;

/**
 * commentsElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentsElementRepository extends \Doctrine\ORM\EntityRepository
{
}
