<?php

namespace CMSBundle\Repository;

/**
 * ContactElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactElementRepository extends \Doctrine\ORM\EntityRepository
{
}
