<?php

namespace CMSBundle\Repository;

/**
 * ElementTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
