<?php

namespace CMSBundle\Repository;

/**
 * MapElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapElementRepository extends \Doctrine\ORM\EntityRepository
{
}
