<?php

namespace CMSBundle\Repository;

/**
 * NavbarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavbarRepository extends \Doctrine\ORM\EntityRepository
{
}
