<?php

namespace CMSBundle\Repository;

/**
 * NavbarLinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavbarLinksRepository extends \Doctrine\ORM\EntityRepository
{
}
