<?php

namespace CMSBundle\Repository;

/**
 * PageImageElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageImageElementRepository extends \Doctrine\ORM\EntityRepository
{
}
