<?php

namespace CMSBundle\Repository;

/**
 * PageCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategoryNames()
    {
        $categoryNames = $this->createQueryBuilder('c')->select('c.name')->getQuery()->getArrayResult();
        $array=[];
        foreach ($categoryNames as $name){
            $array[$name['name']]=$name['name'];
        }
        return $array;
    }
}
