<?php

namespace CMSBundle\Repository;

/**
 * PageListElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageListElementRepository extends \Doctrine\ORM\EntityRepository
{
}
