<?php

namespace CMSBundle\Repository;

/**
 * PgeLinkElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PgeLinkElementRepository extends \Doctrine\ORM\EntityRepository
{
}
