<?php

namespace CMSBundle\Repository;

/**
 * TextElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextElementRepository extends \Doctrine\ORM\EntityRepository
{
}
